#!/bin/bash

SCRIPT_HOME="$(dirname "$(which "$0")")"
source "$SCRIPT_HOME/config"
cd "$PROJECT_DIR"

## Find file name of ROM and set variable
FILE=$(ls $OUT_DIR/target/product/$ANDROID_DEVICE/$ANDROID_VERSION-*.zip)

function build_end {
  if [ "$BUILDER_SHUTODWN" == "true" ]; then
    unset BUILDER_SHUTODWN
    screen -S builder -X quit
  fi
}

## Check if ROM exists before proceding
if [ ! -e "$FILE" ]; then
  echo "Build Failed!"
  build_end
  exit
fi

echo "Build Successful!"

## Generate Last Build File with date of last commit
#date -d "$(repo forall -c 'git log -1 --format=%cI' | sort | tail -1) + 1 second" -Iseconds > "$LAST_BUILD_FILE"

## Remove extension of file name and set variable
NOEXT="$(basename $FILE .zip)"

#echo ""
#echo "Removing previous builds on OTA REST Server."
#echo ""

#rm "$BUILDDIR"/full/cm-14.1-*

echo "Copying ROM $(basename $FILE) to OTA REST Server."

if [ "$OTA_DIR_KEY" != "" ]; then
  scp -i "$OTA_DIR_KEY" "$FILE" "$OTA_DIR/"
else
  cp "$FILE" "$OTA_DIR/"
fi

if [ -e "$CHANGE_FILE" ]; then
  echo "Copying changelog ($NOEXT.html) to OTA REST Server."
  if [ "$OTA_DIR_KEY" != "" ]; then
    scp -i "$OTA_DIR_KEY" "$CHANGE_FILE" "$OTA_DIR/$NOEXT.html"
  else
    cp "$CHANGE_FILE" "$OTA_DIR/$NOEXT.html"
  fi
else
  echo "Changelog not found!"
  echo ""
  exit
fi

echo ""
echo "Done."
echo ""

build_end