#!/bin/bash

SCRIPT_HOME="$(dirname "$(which "$0")")"
source "$SCRIPT_HOME/config"
cd "$PROJECT_DIR"

export LC_ALL=C
export JAVA_HOME=/usr/lib/jvm/default-runtime
export USE_CCACHE=1
export CCACHE_COMPRESS=1
# Path to ccache dir
#export CCACHE_DIR=~/android/system/.ccache
export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4g"
## End Edit

cd "$PROJECT_DIR"
ccache -z
source build/envsetup.sh
make clean
brunch "$ANDROID_DEVICE"
ccache -s
