#!/bin/bash

SCRIPT_HOME="$(dirname "$(which "$0")")"
source "$SCRIPT_HOME/config"

if [ "$1" == "" ]; then
  echo "Error: Destination file required"
  exit
fi

if [ ! -d "$PATCHES_DIR" ]; then
  echo "Error: No patch dir!"
  exit
fi 

echo "Making Patch $1"
echo ""

PREFIX="$(realpath $(git rev-parse --show-toplevel) --relative-to=$PROJECT_DIR)"

git diff --minimal --src-prefix="a/$PREFIX/" --dst-prefix="b/$PREFIX/">"$PATCHES_DIR/$1.diff"

if [ -f "$PATCHES_DIR/$1.diff" ]; then
  more "$PATCHES_DIR/$1"
fi