#!/bin/bash

SCRIPT_HOME="$(dirname "$(which "$0")")"
source "$SCRIPT_HOME/config"
cd "$PROJECT_DIR"

"$SCRIPT_HOME/repo_unpatch"

repo sync --no-clone-bundle -j 8 --force-sync

"$SCRIPT_HOME/repo_patch"


### UNTESTED
if [[ "$(declare -p REBASE_REPOS)" =~ "^declare -a" ]]; then
  for repo in "${REBASE_REPOS[@]}"; do
    if [ -d "$repo" ]; then
      cd "$repo"
      git checkout cm-14.1
      git fetch upstream
      git rebase upstream/cm-14.1
    fi
  done
fi